### ISSUE TITLE
Incorrect shape from jax.numpy.meshgrid

### ISSUE THREAD

**Issue by Methylamphetamine** [astanziola/fourier-neural-operator-flax#1]
Hi, thank you for sharing the FNO implementation in flax. I noticed a problem caused by the indexing method of mesh generation in the file `fno/modules.py` at line 179. The code `jnp.meshgrid(x1, x2)` may produce a mesh whose dimension is `(len(x2), len(x1))` if the shapes of `x1, x2` do not agree. I believe adding the argument `indexing = 'ij'` suffices to fix the problem.

**Comment by astanziola** [comment]
Hello @Methylamphetamine ! Glad that this implementations was useful. Would it work for you to PR a quick fix for this if you already know how to do it? I haven't stared at the code for quite a while.
Otherwise I'll take care of it, thanks a lot for pointing it out.

**Comment by Methylamphetamine** [comment]
Hi @astanziola, I think change the line to `jnp.meshgrid(x1, x2, indexing = 'ij')` would solve the problem. Thank you for still maintaining this repo!
